# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: aws_utils 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "aws_utils"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Anand Bagmar"]
  s.date = "2015-04-07"
  s.description = "Utility methods - like upload / download to and from AWS S3"
  s.email = "abagmar@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "aws_utils.gemspec",
    "lib/aws_utils.rb",
    "lib/utils.rb",
    "lib/zip.rb",
    "spec/aws_utils_spec.rb",
    "spec/resources/input-data.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/anandbagmar/aws_utils"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Utility methods - like upload / download to and from AWS S3"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<pry>, ["= 0.10.1"])
      s.add_development_dependency(%q<rspec>, ["= 3.2.0"])
      s.add_development_dependency(%q<aws-sdk>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<pry>, ["= 0.10.1"])
      s.add_dependency(%q<rspec>, ["= 3.2.0"])
      s.add_dependency(%q<aws-sdk>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<pry>, ["= 0.10.1"])
    s.add_dependency(%q<rspec>, ["= 3.2.0"])
    s.add_dependency(%q<aws-sdk>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

